
version: '3.8'

services:
    web:
        build: .
        volumes:
            - ./:/code
        ports:
            - 8001:8001
        depends_on:
            - "es"

    es:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
        container_name: elasticsearch
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - node.name=es
            - cluster.name=es-docker-cluster
            - cluster.initial_master_nodes=es
            - MAX_LOCKED_MEMORY=unlimited
        volumes:
            - ./es_data_volume:/usr/share/elasticsearch/data
            - ./elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
        ports:
            - 9200:9200
            - 9300:9300